<?php

namespace AppBundle\Repository;

/**
 * SecurityAccessTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecurityAccessTokenRepository extends \Doctrine\ORM\EntityRepository
{
}
