<?php

namespace AppBundle\Repository;

/**
 * SecurityClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecurityClientRepository extends \Doctrine\ORM\EntityRepository
{
}
