<?php

namespace AppBundle\Repository;

/**
 * SecurityRefreshTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecurityRefreshTokenRepository extends \Doctrine\ORM\EntityRepository
{
}
