app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#hwi_oauth_login:
#    path:   /message/login
#    defaults:  { _controller: AppBundle:Security:login }
#
#oauth_logout:
#    path: /message/logout
#
#facebook_login:
#    path: /message/login_facebook

fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /message

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }
