app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#hwi_oauth_login:
#    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
#    prefix:   /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

#hwi_oauth_connect:
#    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
#    prefix:   /connect

hwi_oauth_login:
    path:   /login
    defaults:  { _controller: AppBundle:Security:login }

oauth_logout:
    path: /logout

facebook_login:
    path: /login_facebook
