# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_manager
#        hwi:
#            id: hwi_oauth.user.provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            pattern:    ^/
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

        secured_area:
            pattern: ^/message
            form_login:
                provider: fos_userbundle
                check_path: /message/login_check
                csrf_token_generator: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider

            logout:       true
            anonymous:    true
#        secured_area:
#            anonymous: ~
#            pattern:    ^/message
#            logout: true
#            oauth:
#                resource_owners:
#                    facebook:           "/login_facebook"
#                login_path:        /message/login
##                use_forward:       false
#                failure_path:      /message/login
#                oauth_user_provider:
#                    service: hwi_oauth.user.provider.entity

    access_control:
#        - { path: ^/login,   roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/connect, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/message/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/message/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/message/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/,        roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }

        - { path: ^/message,        roles: [ IS_AUTHENTICATED_FULLY ] }


#        oauth_token:
#            pattern:    ^/oauth/v2/token
#            security:   false
#
#        oauth_authorize:
#            pattern:    ^/oauth/v2/auth
#            # Add your favorite authentication process here
#
#        api:
#            pattern:    ^/api
#            fos_oauth:  true
#            stateless:  true
#            anonymous:  false # can be omitted as its default value

#    access_control:
#        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
