# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        hwi:
            id: hwi_oauth.user.provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
#        main:
#            anonymous: ~
#            form_login:
#                login_path:  /login
#                check_path:  /login_check
#                use_referer: true
#                success_handler: security.login_handler
#                default_target_path: /
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

        secured_area:
            anonymous: ~
            pattern:    ^/
            logout: true
            oauth:
                resource_owners:
                    facebook:           "/login_facebook"
                login_path:        /login
#                use_forward:       false
                failure_path:      /login
                oauth_user_provider:
                    service: hwi_oauth.user.provider.entity

    access_control:
        - { path: ^/login,   roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/,        roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }

        - { path: ^/secure,        roles: [ IS_AUTHENTICATED_FULLY ] }


#        oauth_token:
#            pattern:    ^/oauth/v2/token
#            security:   false
#
#        oauth_authorize:
#            pattern:    ^/oauth/v2/auth
#            # Add your favorite authentication process here
#
#        api:
#            pattern:    ^/api
#            fos_oauth:  true
#            stateless:  true
#            anonymous:  false # can be omitted as its default value

#    access_control:
#        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
